#!/bin/bash
OUT=`echo "$@" | sed -n 's/.* -o \(.*\).*/\1/p' | cut -d " " -f1`
gfortran-4.6 -emit-llvm -S -flto -m32 -fverbose-asm -nostdlib -fplugin=/app/bin/dragonegg.so "$@" && \
sed -i 's/^\(target\sdatalayout\s*=\s*\).*$/\1"e-m:e-p:32:32-i64:64-n32:64-S128"/' "$OUT" && \
sed -i 's/^\(target\striple\s*=\s*\).*$/\1"wasm32-unknown-emscripten"/' "$OUT" && \

# Hardcoded fixes for external fortran symbols
# Required due to a bug in gfortran which creates invalid decl trees
# https://gcc.gnu.org/bugzilla/show_bug.cgi?id=33097
sed -i 's/declare void @kmns1_(\.\.\.)/declare void @kmns1_(i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @kmns1_ to void/void (i32, i32, i32)* @kmns1_ to void/' "$OUT"
sed -i 's/declare void @kmnsqpr_(\.\.\.)/declare void @kmnsqpr_(i32, i32, i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @kmnsqpr_ to void/void (i32, i32, i32, i32, i32)* @kmnsqpr_ to void/' "$OUT"
sed -i 's/declare void @dblep0_(\.\.\.)/declare void @dblep0_(i32, i32, i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @dblep0_ to void/void (i32, i32, i32, i32, i32)* @dblep0_ to void/' "$OUT"
sed -i 's/declare void @rexitc_(\.\.\.)/declare void @rexitc_(i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @rexitc_ to void/void (i32, i32, i32)* @rexitc_ to void/' "$OUT"
sed -i 's/declare void @realp0_(\.\.\.)/declare void @realp0_(i32, i32, i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @realp0_ to void/void (i32, i32, i32, i32, i32)* @realp0_ to void/' "$OUT"
sed -i 's/declare void @ehg184a_(\.\.\.)/declare void @ehg184a_(i32, i32, i32, i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @ehg184a_ to void/void (i32, i32, i32, i32, i32, i32)* @ehg184a_ to void/' "$OUT"
sed -i 's/declare void @intpr0_(\.\.\.)/declare void @intpr0_(i32, i32, i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @intpr0_ to void/void (i32, i32, i32, i32, i32)* @intpr0_ to void/' "$OUT"
sed -i 's/declare void @splineprt_(\.\.\.)/declare void @splineprt_(i32, i32, i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @splineprt_ to void/void (i32, i32, i32, i32, i32)* @splineprt_ to void/' "$OUT"
sed -i 's/declare void @smoothprt_(\.\.\.)/declare void @smoothprt_(i32, i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @smoothprt_ to void/void (i32, i32, i32, i32)* @smoothprt_ to void/' "$OUT"
sed -i 's/declare void @ehg183a_(\.\.\.)/declare void @ehg183a_(i32, i32, i32, i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @ehg183a_ to void/void (i32, i32, i32, i32, i32, i32)* @ehg183a_ to void/' "$OUT"
sed -i 's/declare void @xerbla_(\.\.\.)/declare void @xerbla_(i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @xerbla_ to void/void (i32, i32, i32)* @xerbla_ to void/' "$OUT"
sed -i 's/declare void @rwarnc_(\.\.\.)/declare void @rwarnc_(i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @rwarnc_ to void/void (i32, i32, i32)* @rwarnc_ to void/' "$OUT"
sed -i 's/declare void @sbart_(\.\.\.)/declare void @sbart_(i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @sbart_ to void/void (i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32)* @sbart_ to void/' "$OUT"
sed -i 's/declare void @divset_(\.\.\.)/declare void @divset_(i32, i32, i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @divset_ to void/void (i32, i32, i32, i32, i32)* @divset_ to void/' "$OUT"
sed -i 's/declare void @dn2cvp_(\.\.\.)/declare void @dn2cvp_(i32, i32, i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @dn2cvp_ to void/void (i32, i32, i32, i32, i32)* @dn2cvp_ to void/' "$OUT"
sed -i 's/declare void @ditsum_(\.\.\.)/declare void @ditsum_(i32, i32, i32, i32, i32, i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @ditsum_ to void/void (i32, i32, i32, i32, i32, i32, i32, i32)* @ditsum_ to void/' "$OUT"
sed -i 's/declare void @dv7swp_(\.\.\.)/declare void @dv7swp_(i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @dv7swp_ to void/void (i32, i32, i32)* @dv7swp_ to void/' "$OUT"
sed -i 's/declare void @i7pnvr_(\.\.\.)/declare void @i7pnvr_(i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @i7pnvr_ to void/void (i32, i32, i32)* @i7pnvr_ to void/' "$OUT"
sed -i 's/declare void @dv7scl_(\.\.\.)/declare void @dv7scl_(i32, i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @dv7scl_ to void/void (i32, i32, i32, i32)* @dv7scl_ to void/' "$OUT"
sed -i 's/declare void @dv7ipr_(\.\.\.)/declare void @dv7ipr_(i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @dv7ipr_ to void/void (i32, i32, i32)* @dv7ipr_ to void/' "$OUT"
sed -i 's/declare void @dv7scp_(\.\.\.)/declare void @dv7scp_(i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @dv7scp_ to void/void (i32, i32, i32)* @dv7scp_ to void/' "$OUT"
sed -i 's/declare void @dv7prm_(\.\.\.)/declare void @dv7prm_(i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @dv7prm_ to void/void (i32, i32, i32)* @dv7prm_ to void/' "$OUT"
sed -i 's/declare void @dv7cpy_(\.\.\.)/declare void @dv7cpy_(i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @dv7cpy_ to void/void (i32, i32, i32)* @dv7cpy_ to void/' "$OUT"
sed -i 's/declare void @dv2axy_(\.\.\.)/declare void @dv2axy_(i32, i32, i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @dv2axy_ to void/void (i32, i32, i32, i32, i32)* @dv2axy_ to void/' "$OUT"
sed -i 's/declare i32 @interv_(\.\.\.)/declare i32 @interv_(i32, i32, i32, i32, i32, i32, i32)/' "$OUT"
sed -i 's/i32 (\.\.\.)\* @interv_ to i32/i32 (i32, i32, i32, i32, i32, i32, i32)* @interv_ to i32/' "$OUT"
sed -i 's/declare void @dn2rdp_(\.\.\.)/declare void @dn2rdp_(i32, i32, i32, i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @dn2rdp_ to void/void (i32, i32, i32, i32, i32, i32)* @dn2rdp_ to void/' "$OUT"
sed -i 's/declare void @i7copy_(\.\.\.)/declare void @i7copy_(i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @i7copy_ to void/void (i32, i32, i32)* @i7copy_ to void/' "$OUT"
sed -i 's/declare void @ds7cpr_(\.\.\.)/declare void @ds7cpr_(i32, i32, i32, i32)/' "$OUT"
sed -i 's/void (\.\.\.)\* @ds7cpr_ to void/void (i32, i32, i32, i32)* @ds7cpr_ to void/' "$OUT"
sed -i 's/declare double @dd7tpr_(\.\.\.)/declare double @dd7tpr_(i32, i32, i32)/' "$OUT"
sed -i 's/double (\.\.\.)\* @dd7tpr_ to double/double (i32, i32, i32)* @dd7tpr_ to double/' "$OUT"
sed -i 's/declare double @dv2nrm_(\.\.\.)/declare double @dv2nrm_(i32, i32)/' "$OUT"
sed -i 's/double (\.\.\.)\* @dv2nrm_ to double/double (i32, i32)* @dv2nrm_ to double/' "$OUT"
########

llvm-as-3.3 "$OUT" -o "$OUT.bc" && \
mv "$OUT" "$OUT.ll" && \
mv "$OUT.bc" "$OUT" && \
if [ -z "$KEEP_TEMPS" ]; then rm "$OUT.ll"; fi
